name: Workflow caller - verify changelog updated 
on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - 'INFO_NL.md'
      - 'INFO_UK.md'
      - 'INFO_FR'
      - 'INFO_DE'
      - 'INFO.md'
      - 'Logo.png'
      - 'Icon.png'

jobs:
  verify-changelog:
    uses: Tools4everBV/.github/.github/workflows/verifyChangelog.yaml@main
