name: VerifyChangelog
on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  verify-changelog:
    uses: Tools4everBV/.github/.github/workflows/verifyChangelogV4.yaml@main
